### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luckysmg** [CaiJingLong/flutter_photo_manager#134]
描述：
在调用以下方法后蹦了
 AssetEntity entity =
        await PhotoManager.editor.saveImage(data, title: 'img', desc: 'head');

flutter 1.9.1 hotfix6

**Smartphone (please complete the following information):**
 - Device: 华为P30 pro
 - OS: 安卓10
- 0.4.5

```
报错信息：

```log
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime(31971): 	at android.database.CursorWindow.nativeGetLong(Native Method)
E/AndroidRuntime(31971): 	at android.database.CursorWindow.getLong(CursorWindow.java:542)
E/AndroidRuntime(31971): 	at android.database.CursorWindow.getInt(CursorWindow.java:609)
E/AndroidRuntime(31971): 	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
E/AndroidRuntime(31971): 	at android.database.CursorWrapper.getInt(CursorWrapper.java:126)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.utils.IDBUtils$DefaultImpls.getInt(IDBUtils.kt:99)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.utils.DBUtils.getInt(DBUtils.kt:28)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.utils.DBUtils.getAssetEntity(DBUtils.kt:301)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.utils.AndroidQDBUtils.saveImage(AndroidQDBUtils.kt:381)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.PhotoManager.saveImage(PhotoManager.kt:136)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1$9.invoke(PhotoManagerPlugin.kt:200)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1$9.invoke(PhotoManagerPlugin.kt:95)
E/AndroidRuntime(31971): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime(31971): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime(31971): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime(31971): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(31971): 	at java.lang.Thread.run(Thread.java:929)

```

**Comment by GavinSongBF** [comment]
也遇到相同问题，android 8.0 小米noto3 ;
ios也存在崩溃

**Comment by CaiJingLong** [comment]
The latest version have same problem?

**Comment by luckysmg** [comment]
没有了，最新的版本正常
