### ISSUE TITLE
Android Q : PhotoManagerPlugin get thumb error

### ISSUE THREAD

**Issue by jarkeet** [CaiJingLong/flutter_photo_manager#174]
调起相册的时候，必crash，华为P30
```log
2020-02-01 20:03:18.054 867-16134/? E/MetadataRetrieverClient: failed to extract an album art
2020-02-01 20:03:18.054 11147-20409/? E/MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed.
2020-02-01 20:03:18.056 16677-16677/com.yunjiweidian.daiyan E/PhotoManagerPlugin: get thumb error
    java.io.FileNotFoundException: Failed to create thumbnail
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
        at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1603)
        at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3628)
        at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
        at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
        at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
        at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
        at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3627)
        at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3611)
        at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getThumb(AndroidQDBUtils.kt:363)
        at top.kikt.imagescanner.core.PhotoManager.getThumb(PhotoManager.kt:87)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1.onGranted(PhotoManagerPlugin.kt:179)
        at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:111)
        at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:84)
        at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:284)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2020-02-01 20:03:18.088 867-2300/? E/MetadataRetrieverClient: failed to extract an album art
2020-02-01 20:03:18.089 11147-20409/? E/MediaMetadataRetrieverJNI: getEmbeddedPicture: Call to getEmbeddedPicture failed.
2020-02-01 20:03:18.091 16677-16677/com.yunjiweidian.daiyan E/PhotoManagerPlugin: get thumb error
    java.io.FileNotFoundException: Failed to create thumbnail
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
        at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1603)
        at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3628)
        at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
        at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
        at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
        at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
        at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3627)
        at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3611)
        at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getThumb(AndroidQDBUtils.kt:363)
        at top.kikt.imagescanner.core.PhotoManager.getThumb(PhotoManager.kt:87)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1.onGranted(PhotoManagerPlugin.kt:179)
        at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:111)
        at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:84)
        at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:284)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:363)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by CaiJingLong** [comment]
Keeping the program from crashing is the initial goal of the next version

If possible, I will contact you to provide more information to analyze the cause of the error.

It should be code on a branch, which will contain more log information to help me analyze the code.

**Comment by jarkeet** [comment]
I use version 0.4.8 , it works fine
