### ISSUE TITLE
小米9 选择照片闪退

### ISSUE THREAD

**Issue by wasabia** [CaiJingLong/flutter_photo_manager#182]
```
java.lang.Error: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1202)
	at top.kikt.imagescanner.core.cache.AndroidQCache.getCacheFile(AndroidQCache.kt:47)
	at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getFilePath(AndroidQDBUtils.kt:291)
	at top.kikt.imagescanner.core.PhotoManager.getFile(PhotoManager.kt:140)
	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$5.invoke(PhotoManagerPlugin.kt:210)
	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$5.invoke(PhotoManagerPlugin.kt:23)
	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	... 2 more
```

**Comment by CaiJingLong** [comment]
Can you provide more info to help me located it?

**Comment by laogaoxiaoxin** [comment]
E/AndroidRuntime(10508): Caused by: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(10508):      at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
E/AndroidRuntime(10508):      at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
E/AndroidRuntime(10508):      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
E/AndroidRuntime(10508):      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
E/AndroidRuntime(10508):      at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
E/AndroidRuntime(10508):      at top.kikt.imagescanner.core.cache.AndroidQCache.getCacheFile(AndroidQCache.kt:47)
E/AndroidRuntime(10508):      at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getFilePath(AndroidQDBUtils.kt:291)
E/AndroidRuntime(10508):      at top.kikt.imagescanner.core.PhotoManager.getFile(PhotoManager.kt:140)
E/AndroidRuntime(10508):      at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$5.invoke(PhotoManagerPlugin.kt:210)
E/AndroidRuntime(10508):      at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$5.invoke(PhotoManagerPlugin.kt:23)
E/AndroidRuntime(10508):      at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime(10508):      at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)

华为meta20同样出现了问题，这是一部分崩溃信息。

**Comment by CaiJingLong** [comment]
Just androidQ?

**Comment by laogaoxiaoxin** [comment]
重启了手机之后，就没有问题了，怀疑是写文件那里出现了问题。

**Comment by CaiJingLong** [comment]
Same problem of #144 .
But I can't located the problem.

---

Normally, if the picture has not been deleted, it should not report an error, because this error is thrown by the system API.

**Comment by hahafather007** [comment]
API29权限问题，Manifest中加上```android:requestLegacyExternalStorage="true"```就行了

**Comment by CaiJingLong** [comment]
> API29权限问题，Manifest中加上`android:requestLegacyExternalStorage="true"`就行了

The photo manager's api is written for API29.
No need to add this.
If after you add this, from abnormal to normal, then your problem may be caused by other plugins.

**Comment by CaiJingLong** [comment]
> 重启了手机之后，就没有问题了，怀疑是写文件那里出现了问题。

这种问题通常发生在本地物理文件被其他的app删除, 然后app未通知MediaStore刷新row. 这时读取不存在的文件会报错.

重启恢复正常的原因是重启后MediaStore会自动扫描文件夹, 不存在的item会被删除.

新版本中这个问题不再会引起crash, 但依然会将异常抛出到flutter端, 因为文件真的不存在

**Comment by yy1300326388** [comment]
0.5.8 版本依然存在次问题，我选择的是拼音文件
