### ISSUE TITLE
[BUG] java.lang.IllegalStateException: galleryName must not be null

### ISSUE THREAD

**Issue by doerme** [CaiJingLong/flutter_photo_manager#188]
java.lang.IllegalStateException: galleryName must not be null
        at top.kikt.imagescanner.core.utils.a.getGalleryList(SourceFile:80)
        at top.kikt.imagescanner.core.a.a(SourceFile:41)
        at top.kikt.imagescanner.co
<img width="679" alt="企业微信截图_15822580112760" src="https://user-images.githubusercontent.com/2680224/75003989-b79b4f00-54a4-11ea-818e-44d06d80a0dc.png">
re.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1$1.invoke(SourceFile:118)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1$1.invoke(SourceFile:95)
        at top.kikt.imagescanner.core.d.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by CaiJingLong** [comment]
Just androidQ?

**Comment by CaiJingLong** [comment]
dup of #175.
