### ISSUE TITLE
[BUG] failed to create thumbnail crash

### ISSUE THREAD

**Issue by mhstoller** [CaiJingLong/flutter_photo_manager#220]
**Describe the bug**
When attempting to load an AssetEntity for **EDIT**: a corrupt video (see comment) on an android device, the library crashes with the below output. Seems similar to https://github.com/CaiJingLong/flutter_photo_manager/issues/174 but I am already on version 0.4.8

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: OxygenOS 10.3.2 (based on Android 10, security patch Feb 1, 2020)

**Log**

If applicable, add logs to help explain your problem.

```
E/PhotoManagerPlugin(32227): get thumb error
E/PhotoManagerPlugin(32227): java.io.FileNotFoundException: Failed to create thumbnail
E/PhotoManagerPlugin(32227): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
E/PhotoManagerPlugin(32227): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
E/PhotoManagerPlugin(32227): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
E/PhotoManagerPlugin(32227): 	at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1610)
E/PhotoManagerPlugin(32227): 	at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3636)
E/PhotoManagerPlugin(32227): 	at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
E/PhotoManagerPlugin(32227): 	at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:550)
E/PhotoManagerPlugin(32227): 	at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
E/PhotoManagerPlugin(32227): 	at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
E/PhotoManagerPlugin(32227): 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3635)
E/PhotoManagerPlugin(32227): 	at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3619)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getThumb(AndroidQDBUtils.kt:300)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.core.PhotoManager.getThumb(PhotoManager.kt:85)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.core.PhotoManagerPlugin.onHandlePermissionResult(PhotoManagerPlugin.kt:198)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.core.PhotoManagerPlugin.access$onHandlePermissionResult(PhotoManagerPlugin.kt:23)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onMethodCall$$inlined$apply$lambda$1.onGranted(PhotoManagerPlugin.kt:134)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:129)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.old.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:103)
E/PhotoManagerPlugin(32227): 	at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:145)
E/PhotoManagerPlugin(32227): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/PhotoManagerPlugin(32227): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/PhotoManagerPlugin(32227): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/PhotoManagerPlugin(32227): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/PhotoManagerPlugin(32227): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/PhotoManagerPlugin(32227): 	at android.os.Looper.loop(Looper.java:174)
E/PhotoManagerPlugin(32227): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/PhotoManagerPlugin(32227): 	at java.lang.reflect.Method.invoke(Native Method)
E/PhotoManagerPlugin(32227): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/PhotoManagerPlugin(32227): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/AndroidRuntime(32227): Shutting down VM
E/AndroidRuntime(32227): FATAL EXCEPTION: main
E/AndroidRuntime(32227): Process: com.example.yikyak, PID: 32227
E/AndroidRuntime(32227): java.lang.IllegalArgumentException: Unsupported value: java.io.FileNotFoundException: Failed to create thumbnail
E/AndroidRuntime(32227): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime(32227): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/AndroidRuntime(32227): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/AndroidRuntime(32227): 	at top.kikt.imagescanner.util.ResultHandler$replyError$1.run(ResultHandler.kt:26)
E/AndroidRuntime(32227): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(32227): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(32227): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(32227): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(32227): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32227): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(32227): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (32227): Sending signal. PID: 32227 SIG: 9
```

**Comment by mhstoller** [comment]
Okay, so I believe the issue is not that image actually (just happened to be convenient timing with some other things that made me think it was).

I was messing around with ffmpeg and now have some corrupt video files in my gallery. This is what is causing the crash. I pulled the latest version of photo_manager from git, and the new error from that version is below. It does not crash in the same way, but no thumbnails are loading

```
D/skia    (18382): --- Failed to create image decoder with message 'unimplemented'
W/ExifInterface(18382): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface(18382): java.io.IOException: Invalid byte order: 0
W/ExifInterface(18382): 	at android.media.ExifInterface.readByteOrder(ExifInterface.java:3128)
W/ExifInterface(18382): 	at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2443)
W/ExifInterface(18382): 	at android.media.ExifInterface.getMimeType(ExifInterface.java:2321)
W/ExifInterface(18382): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1755)
W/ExifInterface(18382): 	at android.media.ExifInterface.<init>(ExifInterface.java:1449)
W/ExifInterface(18382): 	at com.bumptech.glide.load.resource.bitmap.ExifInterfaceImageHeaderParser.getOrientation(ExifInterfaceImageHeaderParser.java:40)
W/ExifInterface(18382): 	at com.bumptech.glide.load.ImageHeaderParserUtils.getOrientation(ImageHeaderParserUtils.java:91)
W/ExifInterface(18382): 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decodeFromWrappedStreams(Downsampler.java:236)
W/ExifInterface(18382): 	at com.bumptech.glide.load.resource.bitmap.Downsampler.decode(Downsampler.java:206)
W/ExifInterface(18382): 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:62)
W/ExifInterface(18382): 	at com.bumptech.glide.load.resource.bitmap.StreamBitmapDecoder.decode(StreamBitmapDecoder.java:18)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:515)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:480)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:466)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
W/ExifInterface(18382): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:426)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:387)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
W/ExifInterface(18382): 	at com.bumptech.glide.load.data.mediastore.ThumbFetcher.loadData(ThumbFetcher.java:67)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
W/ExifInterface(18382): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/ExifInterface(18382): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/ExifInterface(18382): 	at java.lang.Thread.run(Thread.java:919)
W/ExifInterface(18382): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
D/skia    (18382): --- Failed to create image decoder with message 'unimplemented'
E/MediaMetadataRetrieverJNI(18382): getFrameAtTime: videoFrame is a NULL pointer
```

If you can find a way to download this file, there is an example of a corrupt video here: https://dl3.pushbulletusercontent.com/gehe6yKAIvMydNEdx1xKHvf0yo0Zl8hs/testvideo1584622301056.mp4

It would be okay for me if the library skipped these files entirely, or if it returned a gray/blank thumbnail

**Comment by CaiJingLong** [comment]
There is no guarantee that MediaStore will not have invalid data.
So I can do is try not to cause a crash exit.
I will try to add some try catch blocks and pass examples to the flutter side.

**Comment by CaiJingLong** [comment]
This problem should have been fixed 2 weeks+, but it was not released to the latest branch of pub.

**Comment by rignaneseleo** [comment]
@CaiJingLong Any news about this fix?
