### ISSUE TITLE
Get AssetPathEntity from it's ID

### ISSUE THREAD

**Issue by TheLastGimbus** [CaiJingLong/flutter_photo_manager#284]
This is exactly the same as issue #267 
There is no good way to get AssetPathEntity without calling whole `PhotoManager.getAssetPathList()`. Static helper function (just like `AssetEntity.fromId()`) would be nice.

**Comment by TheLastGimbus** [comment]
You are FAST :O 
Thank you sooo much!!!

**Comment by TheLastGimbus** [comment]
Sorry, but this doesn't work.
I tried workarounds like this (what you've applied in static function), but I have run into exception after exception, so I decided to make this issue.
Here is the first exception:

```
E/flutter (22584): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter (22584): NoSuchMethodError: The getter 'dateTimeCond' was called on null.
E/flutter (22584): Receiver: null
E/flutter (22584): Tried calling: dateTimeCond
E/flutter (22584): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (22584): #1      AssetPathEntity.refreshPathProperties (package:photo_manager/src/entity.dart:68:27)
E/flutter (22584): #2      AssetPathEntity.fromId (package:photo_manager/src/entity.dart:9:18)

// Below is my code trace - you can ignore it

E/flutter (22584): #3      MemesProvider.syncMemes (package:dotmeme/providers/memes_provider.dart:69:45)
E/flutter (22584): <asynchronous suspension>
E/flutter (22584): #4      PeriodicScan.backgroundScan (package:dotmeme/background/periodic_scan.dart:14:19)
E/flutter (22584): #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (22584): #6      PeriodicScan.backgroundScan (package:dotmeme/background/periodic_scan.dart:9:29)
E/flutter (22584): #7      MyApp.build.<anonymous closure> (package:dotmeme/main.dart:27:20)
E/flutter (22584): #8      new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
E/flutter (22584): #9      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (22584): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

Here are the steps I took to make it work:

```dart
static Future<AssetPathEntity> fromId(String id,
    {FilterOptionGroup filterOption, RequestType type = RequestType.common}) async {
  // Here, you've set filterOption, but did't do anything with it
  filterOption ??= FilterOptionGroup();
  // I replaced this  (final entity = AssetPathEntity()..id = id;)  with below: 
  final entity = AssetPathEntity(id: id, filterOption: filterOption)
    // Also got nullPointerExc on type, so added this
    ..type = type
    // Then, got:
    // 'this.albumType == 1': Just album type can get asset.
    // so set albumType to one (I don't know what about iOS :/ )
    ..albumType = 1;
  await entity.refreshPathProperties();
  return entity;
}
```

This works for now, but it will probably have issues on iOS. If you want, i can make pull request with this.
