### ISSUE TITLE
[Custom] How do I display a large image without OOMs?

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#290]
Currently when I load an image of size 50+MB using `AssetEntity.originBytes`, it triggers an OOM.

##### Crash log:
```
         AndroidRuntime  E  FATAL EXCEPTION: pool-5-thread-1
                         E  Process: io.ente.photos, PID: 19397
                         E  java.lang.OutOfMemoryError: Failed to allocate a 92192544 byte allocation with 12887584 fr
                            ee bytes and 12MB until OOM, target footprint 201326592, growth limit 201326592
                         E      at java.util.Arrays.copyOf(Arrays.java:3161)
                         E      at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
                         E      at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getOriginBytes(AndroidQDBUtils.kt:
                            352)
                         E      at top.kikt.imagescanner.core.PhotoManager.getOriginBytes(PhotoManager.kt:109)
                         E      at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$7.invoke(Pho
                            toManagerPlugin.kt:228)
                         E      at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$7.invoke(Pho
                            toManagerPlugin.kt:23)
                         E      at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown
                            Source:2)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:919)
```

I could choose to load a thumbnail instead if I knew the size beforehand, but that information is not available.

Is there a way to gracefully handle this situation?

Thanks a bunch!

**Comment by vishnukvmd** [comment]
Update: I was able to work around this by using `AssetEntity.file` within `Image.file(...)` instead. 🙂
