### ISSUE TITLE
[Bug] 本地文件删除，通过AssetEntity获取文件。文件不存在，直接crash了

### ISSUE THREAD

**Issue by github0911** [CaiJingLong/flutter_photo_manager#297]
2020-05-26 14:37:27.546 24352-25857/com.xinyan.meet.test E/wulitest:: Thread = pool-4-thread-1
    Throwable = java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/671
2020-05-26 14:37:27.546 24352-25857/com.xinyan.meet.test E/wulitest:: java.lang.Error: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/671
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/671
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1694)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
        at top.kikt.imagescanner.core.cache.AndroidQCache.getCacheFile(AndroidQCache.kt:47)
        at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getFilePath(AndroidQDBUtils.kt:296)
        at top.kikt.imagescanner.core.PhotoManager.getFile(PhotoManager.kt:145)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.kt:218)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.kt:23)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by github0911** [comment]
调用assetEntity.file
