### ISSUE TITLE
选择音频崩溃 [BUG]

### ISSUE THREAD

**Issue by yy1300326388** [CaiJingLong/flutter_photo_manager#340]
**Describe the bug**
选择音频后就崩溃了，Android 10

**To Reproduce**
选择 音频确定后崩溃

**Expected behavior**

```
java.lang.Error: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/video/media/28
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/video/media/28
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1698)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1198)
        at top.kikt.imagescanner.core.cache.AndroidQCache.getCacheFile(AndroidQCache.kt:47)
        at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getFilePath(AndroidQDBUtils.kt:309)
        at top.kikt.imagescanner.core.PhotoManager.getFile(PhotoManager.kt:145)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.kt:225)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.kt:26)
        at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8764899/88475943-f4450800-cf66-11ea-832c-409b2c0f8217.png)

**Flutter version**
```
 Flutter version 1.17.5 at /Users/.../sdk/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
```

**Smartphone (please complete the following information):**
 - Device: 华为 P40
 - OS:Emui 10.1.0
 - Version:Android 10

**Comment by yy1300326388** [comment]
![image](https://user-images.githubusercontent.com/8764899/88476125-7550cf00-cf68-11ea-877c-55715048ff45.png)
修改成这样就可以啦

**Comment by yy1300326388** [comment]
但是视频选择就崩溃了，我稍后会来个 PR

**Comment by CaiJingLong** [comment]
Can you open pull request?
If you have no plan, I will do it.

**Comment by yy1300326388** [comment]
非常感谢，我已经看到新版本了。
我阅读了源码稍后，会继续优化这个，避免重复的代码
