### ISSUE TITLE
[BUG] java.io.FileNotFoundException: No item at content://media/external/images/media/{id}

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#346]
https://github.com/CaiJingLong/flutter_photo_manager/issues/144 was closed, but this issue is still happening *in certain cases* on `v0.5.6` when a file is deleted outside my app.

For some odd reason, this issue is consistently reproducible within the "Screenshots" folder on a OnePlus 5. 🤷 

Within every other folder, `AssetEntity.fromId(...)` returns `null` once the file has been deleted, and I'm able to handle the issue gracefully.

Within the "Screenshots" folder, calling `AssetEntity.fromId(...)` on a file that was deleted from the default gallery app returns a non-null asset, whose `thumbDataWithSize` returns `null` and `file` crashes the application with the following stack trace:
```
 java.lang.Error: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/186150
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:919)
                         E  Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/186150
                         E      at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
                         E      at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
                         E      at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
                         E      at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
                         E      at android.content.ContentResolver.openInputStream(ContentResolver.java:1205)
                         E      at top.kikt.imagescanner.core.cache.AndroidQCache.getCacheFile(AndroidQCache.kt:48)
                         E      at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getFilePath(AndroidQDBUtils.kt:309)
                         E      at top.kikt.imagescanner.core.PhotoManager.getFile(PhotoManager.kt:145)
                         E      at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.kt:225)
                         E      at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.kt:26)
                         E      at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      ... 2 more
```

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by vishnukvmd** [comment]
I haven't run into it since then.
