### ISSUE TITLE
permission Bug

### ISSUE THREAD

**Issue by PreviousTlx** [CaiJingLong/flutter_photo_manager#357]
android原生项目添加flutter。在使用的时候出现这个问题。请问有办法规避下么？因为我在之前就已经进行权限判断了。
```
E/MethodChannel#top.kikt/photo_manager: Failed to handle method call
    java.lang.NullPointerException: 获取权限的Activity不存在
        at top.kikt.imagescanner.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:110)
        at top.kikt.imagescanner.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:95)
        at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:157)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:379)
        at android.os.Looper.loop(Looper.java:144)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by dong199101** [comment]
你看下是不是 #355 提到的问题；可以先修复一下，然后等作者更新；

**Comment by PreviousTlx** [comment]
> 你看下是不是 #355 提到的问题；可以先修复一下，然后等作者更新；

我看了下源码，不知道是不是跟两种初始化PhotoManagerPlugin有关，一种通过flutterEngine(这种会导致activity为Null)，一种通过register的方式。目前这个问题会导致拿不到相册的数据。

**Comment by PreviousTlx** [comment]
> 你看下是不是 #355 提到的问题；可以先修复一下，然后等作者更新；

请问下，你也是用的混编模式么？Android+flutter？这种情况如何修复？

**Comment by PreviousTlx** [comment]
> 你看下是不是 #355 提到的问题；可以先修复一下，然后等作者更新；

我刚试出来一个api，貌似解决了。现在能拿到数据而且也不报错了。

**Comment by PreviousTlx** [comment]
> 你看下是不是 #355 提到的问题；可以先修复一下，然后等作者更新；

flutterEngine.getActivityControlSurface().attachToActivity
