### ISSUE TITLE
[BUG]  kotlin.UninitializedPropertyAccessException: lateinit property durationConstraint has not been initialized.

### ISSUE THREAD

**Issue by samuelezedi** [CaiJingLong/flutter_photo_manager#425]
I get this bug when I try to access the widget on android, but it works fine on IOS, what could be the problem.

```
kotlin.UninitializedPropertyAccessException: lateinit property durationConstraint has not been initialized
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.entity.FilterCond.durationArgs(FilterOption.kt:44)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.utils.IDBUtils$DefaultImpls.getCondFromType(IDBUtils.kt:250)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getCondFromType(AndroidQDBUtils.kt:36)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.utils.DBUtils.getOnlyGalleryList(DBUtils.kt:73)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.PhotoManager.getGalleryList(PhotoManager.kt:39)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:179)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:25)
E/AndroidRuntime(16648):        at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime(16648):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(16648):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(16648):        at java.lang.Thread.run(Thread.java:764)
I/Process (16648): Sending signal. PID: 16648 SIG: 9
Lost connection to device.
```
I get this bug when I try to access the widget on android, but it works fine on IOS, what could be the problem.

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
