### ISSUE TITLE
NPE in ImageScanner

### ISSUE THREAD

**Issue by vishna** [CaiJingLong/flutter_photo_manager#43]
I've run into this condition...

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'top.kikt.imagescanner.AssetType top.kikt.imagescanner.Asset.getType()' on a null object reference
        at top.kikt.imagescanner.ImageScanner.filterImagePath(ImageScanner.kt:535)
        at top.kikt.imagescanner.ImageScanner.access$filterImagePath(ImageScanner.kt:14)
        at top.kikt.imagescanner.ImageScanner$getImagePathIdList$1.run(ImageScanner.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:7
```

appears `img.type` might throw [here](https://github.com/CaiJingLong/flutter_photo_manager/blob/master/android/src/main/kotlin/top/kikt/imagescanner/ImageScanner.kt#L535)

**Comment by CaiJingLong** [comment]
Update to beta.2 to see this change.
