### ISSUE TITLE
[BUG] Crash when calling `getAssetPathList()` on Android 10.

### ISSUE THREAD

**Issue by hworld** [CaiJingLong/flutter_photo_manager#438]
**Describe the bug**
Getting a fatal crash of the app when calling `PhotoManager.getAssetPathList()`. Log is below.

**To Reproduce**
```
final result = await PhotoManager.requestPermission();
if (result == true) {
  final paths = await PhotoManager.getAssetPathList();
}
```
It will crash on the line to get the asset path list. I tried requesting just images, just videos, and with onlyAll set and without. It always crashes fatally with the same error.

**Expected behavior**

**Screenshots**

**Flutter version**
1.25.0-8.3.pre (the beta release channel)
compileSdkVersion 29
targetSdkVersion 29
minSdkVersion 21
I have `android:requestLegacyExternalStorage="true"` set in my AndroidManifest.xml.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A10e
 - OS: Android
 - Version: 10

I don't get any errors on an Android 11 device I have for testing (Pixel 2 XL) and it seems to work on a really ancient Samsung J2 Prime (Android 6).

**Log**

```
E/AndroidRuntime(18959): FATAL EXCEPTION: pool-23-thread-1
E/AndroidRuntime(18959): Process: com.app.app, PID: 18959
E/AndroidRuntime(18959): java.lang.IllegalArgumentException: Invalid column count(1)
E/AndroidRuntime(18959): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
E/AndroidRuntime(18959): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/AndroidRuntime(18959): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
E/AndroidRuntime(18959): 	at android.content.ContentResolver.query(ContentResolver.java:951)
E/AndroidRuntime(18959): 	at android.content.ContentResolver.query(ContentResolver.java:887)
E/AndroidRuntime(18959): 	at android.content.ContentResolver.query(ContentResolver.java:843)
E/AndroidRuntime(18959): 	at top.kikt.imagescanner.core.utils.DBUtils.getOnlyGalleryList(DBUtils.kt:82)
E/AndroidRuntime(18959): 	at top.kikt.imagescanner.core.PhotoManager.getGalleryList(PhotoManager.kt:48)
E/AndroidRuntime(18959): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:213)
E/AndroidRuntime(18959): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$1.invoke(PhotoManagerPlugin.kt:29)
E/AndroidRuntime(18959): 	at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(Unknown Source:2)
E/AndroidRuntime(18959): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(18959): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(18959): 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by hworld** [comment]
I spun up an emulator of Pixel 2 / Android 10 (API 29 with Play), and I couldn't reproduce it there. I'm only able to consistently repro on the actual Galaxy A10e device.

If there's anything further I can test/try out, let me know. I don't really know how to debug this, but I'll happily give anything a go.

**Comment by hworld** [comment]
When I restarted the device, it magically started working. Hurray?
