### ISSUE TITLE
[BUG] An error occurs when invoking the 'PhotoManager.setLog(false)'

### ISSUE THREAD

**Issue by veritasware** [CaiJingLong/flutter_photo_manager#473]
An error occurs when invoking the 'PhotoManager.setLog(false)'

Other functions work well.

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method log on channel top.kikt/photo_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      Plugin.setLog (package:photo_manager/src/plugin.dart:132:5)
<asynchronous suspension>
```

**Comment by AlexV525** [comment]
Platform?
