### ISSUE TITLE
[BUG] java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original

### ISSUE THREAD

**Issue by nkek1027** [CaiJingLong/flutter_photo_manager#479]
**Describe the bug**
`Fatal Exception: java.lang.UnsupportedOperationException: Caller must hold ACCESS_MEDIA_LOCATION permission to access original
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderProxy.java:705)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1694)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
       at top.kikt.imagescanner.core.cache.AndroidQCache.getCacheFile(AndroidQCache.java:46)
       at top.kikt.imagescanner.core.utils.AndroidQDBUtils.getFilePath(AndroidQDBUtils.java:305)
       at top.kikt.imagescanner.core.PhotoManager.getFile(PhotoManager.java:146)
       at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.java:227)
       at top.kikt.imagescanner.core.PhotoManagerPlugin$onHandlePermissionResult$6.invoke(PhotoManagerPlugin.java:25)
       at top.kikt.imagescanner.core.PhotoManagerPlugin$sam$java_lang_Runnable$0.run(PhotoManagerPlugin.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)`

**To Reproduce**
1. Android media picker click

**Screenshots**
<img width="1019" alt="스크린샷 2021-04-16 오후 6 34 24" src="https://user-images.githubusercontent.com/32190151/115005276-aa2ff800-9ee2-11eb-8124-b46435591e27.png">

**Flutter version**
1.22.6

**Smartphone (please complete the following information):**
 - Device: Galaxy S9, Galaxy S9, Galaxy S9+, Galaxy A8 Star, Redmi K30
 - OS: Android 10, 11

**Log**

If applicable, add logs to help explain your problem.

```bash

```

**Comment by CaiJingLong** [comment]
Please provide next info:

1. Android version version
1.  compile SDK version
1. target SDK version

**Comment by nkek1027** [comment]
Android device version : android 10
compile SDK version : 29
target SDK version : 29

**Comment by ybin0823** [comment]
We are using version 0.5.8.

It looks like it was modified from 1.0.0, is it the same cause?
https://github.com/CaiJingLong/flutter_photo_manager/commit/440ef906354c87ca47c29ffd1d10158a705e5cf5#diff-2b4e75f98bb042b63d1fa3903a4af07cdbcd8fb54437ce26093b60872c2643e5

**Comment by AlexV525** [comment]
See https://github.com/CaiJingLong/flutter_photo_manager#remove-media-location-permission .
