### ISSUE TITLE
[BUG] PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)

### ISSUE THREAD

**Issue by vishnukvmd** [CaiJingLong/flutter_photo_manager#589]
**Describe the bug**
Calling `asset.originFile` is throwing the following exception on certain devices:

```
⤷ error: PlatformException(PERMISSION_REQUESTING, Another permission request is still ongoing. Please request after the existing one is done., null, null)
⤷ trace: #0      _getMediaUploadDataFromAssetFile.<anonymous closure> (package:photos/utils/file_uploader_util.dart:63)
#1      _getMediaUploadDataFromAssetFile.<anonymous closure> (package:photos/utils/file_uploader_util.dart:58)
#2      _rootRunUnary (dart:async/zone.dart:1362)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265)
#4      _FutureListener.handleError (dart:async/future_impl.dart:172)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:719)
#6      Future._propagateToListeners (dart:async/future_impl.dart:740)
#7      Future._completeError (dart:async/future_impl.dart:550)
#8      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:819)
#9      _rootRunBinary (dart:async/zone.dart:1378)
#10     _CustomZone.runBinary (dart:async/zone.dart:1272)
#11     _FutureListener.handleError (dart:async/future_impl.dart:169)
#12     Future._propagateToListeners.handleError (dart:async/future_impl.dart:719)
#13     Future._propagateToListeners (dart:async/future_impl.dart:740)
#14     Future._completeError (dart:async/future_impl.dart:550)
#15     _completeOnAsyncError (dart:async-patch/async_patch.dart:274)
#16     PhotoManager._getFileWithId (package:photo_manager/src/manager.dart)
<asynchronous suspension>
```

The users have confirmed that they have granted the permissions (which we too could verify from application logs), and that they did not revoke the permissions after granting them. In that case why are we making an additional permission request and blocking on it?

**To Reproduce**
Unable to reproduce on our devices

**Expected behavior**
`asset.originFile` should return the file and not throw this error if permission has already been granted.

**Screenshots**
N/A

**Flutter version**:  2.2.3
**flutter_photo_manager version**: 1.2.8

**Smartphone (please complete the following information):**
 - Devices: Pixel 2, Pixel 3, Pixel 3a, Pixel 3XL, Pixel 4, Pixel 4XL Pixel 5, ONEPLUS A6003, KB2005, SM-G991U1, SM-F926U, SM-G986B, SM-G988B, Redmi Note 8 Pro, Redmi Note 9 Pro, Mi Note 10 Pro, Redmi K20, Xperia XZ2 Compact (from Sentry error logs)
 - OS: Android 10, 11, 12

Not sure if this is related to https://github.com/CaiJingLong/flutter_photo_manager/issues/563.

**Comment by AlexV525** [comment]
I can't test with an older version.

**Comment by vishnukvmd** [comment]
@AlexV525 We released a new build with v1.3.1, and the issue is being reported there too.

**Comment by AlexV525** [comment]
Any sample code?

**Comment by vishnukvmd** [comment]
Hey @AlexV525 , there are two points where this is being triggered from:

1. https://github.com/ente-io/frame/blob/master/lib/utils/file_sync_util.dart#L115-L119
2. https://github.com/ente-io/frame/blob/master/lib/utils/file_uploader_util.dart#L56-L65

These code paths are invoked only after users have granted permissions to their gallery. Please let me know what we are missing.

**Comment by AlexV525** [comment]
Your code involved with multiple inline callers. Can you confirm whether you've called these _permission requested_ callers in the same time like using some iterator?

**Comment by vishnukvmd** [comment]
1. `PhotoManager.getAssetPathList` is invoked only once. Multiple calls are never made in parallel.
2. But `asset.originFile` could be invoked multiple times in parallel (like while displaying the gallery grid view or while uploading files in parallel).

**Comment by AlexV525** [comment]
I suggest you take an extra peission request before those parallel callers and wait until it's done.

**Comment by vishnukvmd** [comment]
@AlexV525 So most of the errors are from `PhotoManager.getAssetPathList`, which is not called in parallel.

Also, this is invoked from the background (when there is no activity), which will fail as per https://github.com/CaiJingLong/flutter_photo_manager/issues/581#issuecomment-894094353?

**Comment by AlexV525** [comment]
Are you familiar with native Android? Can you take some debugging or provide a minimal project to repro this?

**Comment by vishnukvmd** [comment]
In the foreground, we started issuing an additional permission request and in the background we disabled permission checks, and this fixed the issue. Thanks for the tip @AlexV525 !

**Comment by Tienisto** [comment]
This still occurs on Samsung Galaxy S21 (photo manager v2.5.2)

**Comment by Y-ndm** [comment]
> This still occurs on Samsung Galaxy S21 (photo manager v2.5.2).
> 
> The error is raised by accessing multiple `AssetEntity.originFile` in parallel right after first permission grant.
> 
> ```dart
> final List<AssetEntity> assets;
> // [...]
> final Iterable<File> files = await Future.wait(
>   assets.map((asset) async => (await asset.originFile)!),
> );
> ```

This ☝️ is still happening with me too. device: Samsung Galaxy A23.
