### ISSUE TITLE
PlatformException when running in Isolate (using plugins that support platform code)

### ISSUE THREAD

**Issue by vpsq** [CaiJingLong/flutter_photo_manager#591]
Good day! Could you help?

I am experiencing PlatformException when running PhotoManager in an isolate using a plugin that supports running platform code in an isolate. 
More info:

Target API: 29
Dart SDK: 2.13.4
Flutter: 2.2.3

pubspec.yaml:
```yaml
isolate_handler: 1.0.0
photo_manager: ^1.3.1
```

```java
Exception has occurred.
PlatformException (PlatformException(error, Activity for the permission request is not exist., null, java.lang.NullPointerException: Activity for the permission request is not exist.
	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissionsWithTips(PermissionsUtils.java:116)
	at top.kikt.imagescanner.permission.PermissionsUtils.getPermissions(PermissionsUtils.java:102)
	at top.kikt.imagescanner.core.PhotoManagerPlugin.onMethodCall(PhotoManagerPlugin.kt:221)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
))

```

```dart
import 'package:flutter/material.dart';

/// Welcome to the Isolate Handler example
///
/// In this example we will take a look at how to spawn an isolate and allow it
/// to communicate with the main isolate. The isolate will be using a plugin, too.
///
/// This will be a simple, but complete project. We will start an isolate and
/// send it a string, have it add a path to it and return the value.
///
/// We will also give our isolate a name to make it easy to access from
/// anywhere.

import 'package:isolate_handler/isolate_handler.dart';
// import 'package:path_provider/path_provider.dart';
import 'package:photo_manager/photo_manager.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
// Let's create a new IsolateHandler instance. This is what we will use
// to spawn isolates.
  final isolates = IsolateHandler();

// Variable where we can store the message.
  String isolateMessage = '';

  @override
  void initState() {
    super.initState();

    isolates.spawn<String>(entryPoint,
        name: 'isolate',
        onReceive: communicationFromIsolate,
        onInitialized: () => isolates.send("test", to: "isolate"));
  }

  void communicationFromIsolate(dynamic data) {
    // Show the new message.
    setState(() {
      isolateMessage = data.toString();
    });

    // We will no longer be needing the isolate, let's dispose of it.
    isolates.kill('isolate');
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Isolate Handler example'),
          ),
          body: Center(child: Text(isolateMessage)),
        ),
      );
}

// This function happens in the isolate.
void entryPoint(Map<String, dynamic> context) async {
  final messenger = HandledIsolate.initialize(context);

  messenger.listen((msg) async {
    // Use a plugin to get some new value to send back to the main isolate.
    List<AssetPathEntity> _deviceAlbumList =
        await PhotoManager.getAssetPathList(onlyAll: true);
    messenger.send(_deviceAlbumList.length);
  });
}



```

**Comment by vpsq** [comment]
2nd test: 
using `flutter_isolate` plugin and obtaining Permissions at app start.

Still get the `PlatformException`.  

Please see code using `flutter_isolate` plugin below:

```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter_isolate/flutter_isolate.dart';
// import 'package:path_provider/path_provider.dart';
import 'package:photo_manager/photo_manager.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:io';

void main() async {
  runApp(MyApp());
}

void isolatePhotoMgr(String arg) async {
  await PhotoManager.getAssetPathList(onlyAll: true);
}

Future<bool> getPermissions() async {
  var permission = Platform.isAndroid ? Permission.storage : Permission.photos;
  var status = await permission.status;
  switch (status) {
    case PermissionStatus.denied:
      status = await permission.request();
      if (status == PermissionStatus.permanentlyDenied) {
        return openAppSettings();
      }
      return status == PermissionStatus.granted;
    // break;
    case PermissionStatus.granted:
      return true;
    // break;
    case PermissionStatus.restricted:
      return false;
    case PermissionStatus.limited:
      return false;
    case PermissionStatus.permanentlyDenied:
      return openAppSettings();
  }
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();

    getPermissions().then((value) {
      print("Got permissions" + value.toString());
    });
  }

  Future<void> _run() async {
    final isolate =
        await FlutterIsolate.spawn(isolatePhotoMgr, "isolatePhotoMgr");
    Timer(Duration(seconds: 30), () {
      print("Killing Isolate PhotoMgr");
      isolate.kill();
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: ElevatedButton(
            child: Text('Run'),
            onPressed: _run,
          ),
        ),
      ),
    );
  }
}


```

**Comment by AlexV525** [comment]
This means the plugin has been attached to an activity yet or detached, and permission requests require an activity.

**Comment by vpsq** [comment]
So what's the workaround? Or fix? Right now, its not possible to run this in an isolate.

**Comment by vpsq** [comment]
Tried that, same error and issue.  Any way to pass the permissions from the UI  to the isolate and then into your plugin?  

Am using `permissions_handler` plugin (3rd party plugin) , so should I set this?

```
 static Future<void> setIgnorePermissionCheck(bool ignore) async {
    await _plugin.ignorePermissionCheck(ignore);
  }
```

**Comment by AlexV525** [comment]
Sure. If you're pretty sure that your calls will definitely have granted with permissions, you can ignore it.

**Comment by vpsq** [comment]
Yes, the call to `setIgnorePermissionCheck()` seems to have fixed it.  Have only used `getAssetPathList()` for now, but this is encouraging.   Closing issue.
