### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ashkryab** [CaiJingLong/flutter_photo_manager#64]
FATAL EXCEPTION: pool-2-thread-1
Process: com.app1551.prod, PID: 2090
java.lang.ArrayIndexOutOfBoundsException: length=49; index=49
	at java.util.ArrayList.indexOf(ArrayList.java:331)
	at java.util.ArrayList.contains(ArrayList.java:314)
	at top.kikt.imagescanner.ImageScanner.handleImageCursor(ImageScanner.kt:148)
	at top.kikt.imagescanner.ImageScanner.scanImage(ImageScanner.kt:125)
	at top.kikt.imagescanner.ImageScanner.access$scanImage(ImageScanner.kt:16)
	at top.kikt.imagescanner.ImageScanner$getImagePathIdList$1.run(ImageScanner.kt:550)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
FATAL EXCEPTION: pool-2-thread-2
Process: com.app1551.prod, PID: 2090
java.lang.ArrayIndexOutOfBoundsException: length=49; index=49
	at java.util.ArrayList.add(ArrayList.java:468)
	at top.kikt.imagescanner.ImageScanner.handleImageCursor(ImageScanner.kt:149)
	at top.kikt.imagescanner.ImageScanner.scanImage(ImageScanner.kt:125)
	at top.kikt.imagescanner.ImageScanner.access$scanImage(ImageScanner.kt:16)
	at top.kikt.imagescanner.ImageScanner$getImagePathIdList$1.run(ImageScanner.kt:550)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

**Comment by CaiJingLong** [comment]
Operating and reproducing steps.
In addition, provide the call place code.

**Comment by ashkryab** [comment]
due to accessing to your ArrayList from multiple threads.

ArrayList isn't synchronised and so isn't thread safe. If this is the problem you can fix it by wrapping your List using Collections.synchronizedList().

**Comment by CaiJingLong** [comment]
Although there are multiple threads accessing ArrayList
But in fact, the dart side should await and call the corresponding method sequentially to trigger the original scanning method, so for efficiency reasons, no synchronization method is used.

Because I don't know under what circumstances you triggered this error, you can try to fix the thread problem locally.
If it's determined that the problem is caused by multithreading, I will fix it.

**Comment by ashkryab** [comment]
yes, it is my fault. 2 parallel calls. thanks for the answer
