### ISSUE TITLE
[BUG] crash when call getAssetPathList second time!

### ISSUE THREAD

**Issue by trantrongkim98** [CaiJingLong/flutter_photo_manager#65]
**Describe the bug**
when i call methob getAssetPathList second time my app has crashed immediately
and I found it comes from an error when I use the isCache = false ;
**Expected behavior**
pathList = await PhotoManager.getAssetPathList(hasVideo:true,isCache:true);

**Flutter version**

**Smartphone (please complete the following information):**
 - Device: [e.g. MIPAD4]
 - Version [3.0.1]

**Log**

```
java.lang.ArrayIndexOutOfBoundsException: length=823; index=823
[        ] E/AndroidRuntime(15281): 	at java.util.ArrayList.add(ArrayList.java:468)
[        ] E/AndroidRuntime(15281): 	at top.kikt.imagescanner.ImageScanner.handleImageCursor(ImageScanner.kt:149)
[        ] E/AndroidRuntime(15281): 	at top.kikt.imagescanner.ImageScanner.scanImage(ImageScanner.kt:125)
[        ] E/AndroidRuntime(15281): 	at top.kikt.imagescanner.ImageScanner.scan(ImageScanner.kt:79)
[        ] E/AndroidRuntime(15281): 	at top.kikt.imagescanner.ImageScanner.access$scan(ImageScanner.kt:16)
[        ] E/AndroidRuntime(15281): 	at top.kikt.imagescanner.ImageScanner$scanAndGetImageIdList$1.run(ImageScanner.kt:219)
[        ] E/AndroidRuntime(15281): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[        ] E/AndroidRuntime(15281): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[        ] E/AndroidRuntime(15281): 	at java.lang.Thread.run(Thread.java:764)

```

**Comment by TimonBozzApps** [comment]
Same for me

**Comment by CaiJingLong** [comment]
Update version to 0.4.1.
